### ISSUE TITLE
Section outdated: Creating and editing a raster store

### ISSUE THREAD

**Issue by lexvand** [nens/lizard-docs#52]
This section is no longer up-to-date: https://docs.lizard.net/d_general.html#creating-and-editing-a-raster-store

In another section on raster management I updated the workflow (concisely): https://docs.lizard.net/c_rasters.html

Question is:
- Why is this documented twice?
- How to clean it up?
- Is the new description clear enough?

**Comment by lisannewapstra** [comment]
yours looks better! I removed more from this chapter
